"""
CREATIVE-ENGINE — Generative AI & Multimedia Synthesis
=======================================================
Text-to-image prompting, content generation, 3D scene descriptions,
audio composition, and real-time rendering pipeline hooks.
"""
from __future__ import annotations

import base64
import html
import io
import re
import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

import structlog

log = structlog.get_logger("brainiac.creative_engine")


class MediaType(str, Enum):
    IMAGE = "image"
    VIDEO = "video"
    AUDIO = "audio"
    THREE_D = "3d"
    TEXT = "text"
    CODE = "code"


class Style(str, Enum):
    PHOTOREALISTIC = "photorealistic"
    CINEMATIC = "cinematic"
    ILLUSTRATION = "illustration"
    TECHNICAL = "technical"
    ABSTRACT = "abstract"
    PIXEL_ART = "pixel_art"
    THREE_D_RENDER = "3d_render"
    BLUEPRINT = "blueprint"


@dataclass
class CreativeAsset:
    asset_id: str
    media_type: MediaType
    prompt: str
    style: Style
    data: bytes | str
    format: str
    width: int | None = None
    height: int | None = None
    duration_s: float | None = None
    created_at: float = field(default_factory=time.time)
    generation_ms: float = 0.0
    metadata: dict = field(default_factory=dict)

    def to_base64(self) -> str:
        if isinstance(self.data, bytes):
            return base64.b64encode(self.data).decode()
        return base64.b64encode(self.data.encode()).decode()


class CreativeEngine:
    """
    CREATIVE-ENGINE — generative multimedia synthesis.

    Integration Points
    ------------------
    - Image: DALL-E 3 / Stability AI / Midjourney API
    - Video: RunwayML / Sora API (when available)
    - Audio: ElevenLabs / Suno / custom models
    - 3D: Shap-E / Meshy / Three.js scene generation
    - Code: NEURO-CORE code-generation path
    """

    def __init__(self) -> None:
        import uuid
        self._uuid = uuid
        self._assets: dict[str, CreativeAsset] = {}
        self._generation_count = 0
        log.info("creative_engine.init")

    # ── Text Generation ───────────────────────────────────────────────────────

    def generate_text(
        self,
        prompt: str,
        style: Style = Style.TECHNICAL,
        max_length: int = 2000,
    ) -> CreativeAsset:
        """Generate structured text content (report, story, code, etc.)."""
        t0 = time.perf_counter()
        # Content is produced by NEURO-CORE in production; stub here
        content = (
            f"[CREATIVE-ENGINE: {style.value.upper()} GENERATION]\n"
            f"Prompt: {prompt}\n\n"
            f"[This output is generated by BRAINIAC NEURO-CORE via CreativeEngine.]\n"
            f"{'─' * 60}\n"
            f"Generated content would appear here at production runtime, "
            f"powered by Claude Opus 4.6 with style={style.value}."
        )
        elapsed = (time.perf_counter() - t0) * 1000
        return self._make_asset(content.encode(), "txt", MediaType.TEXT, prompt, style, elapsed)

    # ── Image Generation ──────────────────────────────────────────────────────

    def generate_image_prompt(
        self,
        subject: str,
        style: Style = Style.PHOTOREALISTIC,
        width: int = 1024,
        height: int = 1024,
    ) -> dict[str, Any]:
        """
        Construct an optimised DALL-E 3 / Stable Diffusion prompt.
        Returns the prompt dict ready to send to the image API of choice.
        """
        style_modifiers = {
            Style.PHOTOREALISTIC: "ultra-realistic, 8K, professional photography, RAW",
            Style.CINEMATIC: "cinematic lighting, anamorphic lens, film grain, dramatic",
            Style.ILLUSTRATION: "detailed digital illustration, vibrant colours, concept art",
            Style.TECHNICAL: "technical diagram, clean lines, engineering blueprint style",
            Style.ABSTRACT: "abstract art, fluid shapes, bold palette, generative",
            Style.PIXEL_ART: "pixel art, 32-bit, crisp edges, retro game style",
            Style.THREE_D_RENDER: "3D render, octane renderer, subsurface scattering, HDR",
            Style.BLUEPRINT: "engineering blueprint, white lines on blue, technical drawing",
        }
        optimised = f"{subject}, {style_modifiers[style]}, highly detailed"
        return {
            "prompt": optimised,
            "size": f"{width}x{height}",
            "style": style.value,
            "quality": "hd",
            "model": "dall-e-3",
        }

    # ── 3D Scene ──────────────────────────────────────────────────────────────

    def generate_3d_scene(self, description: str) -> dict[str, Any]:
        """
        Generate a Three.js scene configuration from a text description.
        In production: call Shap-E or Meshy API.
        """
        return {
            "scene": description,
            "threejs_config": {
                "renderer": "WebGLRenderer",
                "antialias": True,
                "shadowMap": "PCFSoftShadowMap",
                "camera": {"fov": 75, "near": 0.1, "far": 1000, "position": [0, 5, 10]},
                "lighting": [
                    {"type": "AmbientLight", "color": "#ffffff", "intensity": 0.5},
                    {"type": "DirectionalLight", "color": "#ffffff", "intensity": 1.0,
                     "position": [10, 20, 10], "castShadow": True},
                ],
                "objects": [],     # populated by 3D model API response
            },
            "generation_note": "Connect Shap-E or Meshy API to populate objects[]",
        }

    # ── Audio Composition ─────────────────────────────────────────────────────

    def compose_audio_spec(
        self,
        mood: str,
        duration_s: float = 30.0,
        instruments: list[str] | None = None,
    ) -> dict[str, Any]:
        """Generate an audio composition specification (for Suno / AudioCraft)."""
        instruments = instruments or ["synthesizer", "bass", "drums"]
        return {
            "mood": mood,
            "duration_s": duration_s,
            "instruments": instruments,
            "bpm": self._mood_to_bpm(mood),
            "key": "C_major",
            "generation_api": "suno_v3",
            "prompt": f"Compose a {duration_s:.0f}-second {mood} track with {', '.join(instruments)}",
        }

    # ── SVG / Vector ──────────────────────────────────────────────────────────

    def generate_svg_badge(self, text: str, color: str = "#00f5ff") -> str:
        """Generate a simple SVG status badge."""
        # Validate color: only allow valid hex colors to prevent attribute injection
        if not re.match(r"^#[0-9a-fA-F]{3}(?:[0-9a-fA-F]{3})?$", color):
            color = "#00f5ff"
        safe_text = html.escape(text, quote=True)
        width = max(60, len(text) * 8 + 20)
        return (
            f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="20">'
            f'<rect width="{width}" height="20" rx="3" fill="#0d0d0d"/>'
            f'<text x="{width//2}" y="14" font-family="monospace" font-size="11" '
            f'fill="{color}" text-anchor="middle">{safe_text}</text>'
            f'</svg>'
        )

    # ── Internals ─────────────────────────────────────────────────────────────

    def _make_asset(
        self,
        data: bytes,
        fmt: str,
        media_type: MediaType,
        prompt: str,
        style: Style,
        elapsed_ms: float,
    ) -> CreativeAsset:
        asset_id = self._uuid.uuid4().hex[:12]
        asset = CreativeAsset(
            asset_id=asset_id,
            media_type=media_type,
            prompt=prompt,
            style=style,
            data=data,
            format=fmt,
            generation_ms=round(elapsed_ms, 2),
        )
        self._assets[asset_id] = asset
        self._generation_count += 1
        log.info("creative_engine.asset_created", id=asset_id, type=media_type.value, ms=elapsed_ms)
        return asset

    @staticmethod
    def _mood_to_bpm(mood: str) -> int:
        table = {"calm": 70, "happy": 120, "epic": 140, "tense": 160, "sad": 60, "energetic": 130}
        return table.get(mood.lower(), 100)

    # ── Diagnostics ───────────────────────────────────────────────────────────

    def diagnostics(self) -> dict[str, Any]:
        type_counts: dict[str, int] = {}
        for a in self._assets.values():
            type_counts[a.media_type.value] = type_counts.get(a.media_type.value, 0) + 1
        return {
            "status": "ONLINE",
            "navigation_role": "map_and_badge_renderer",
            "capabilities": ["svg_badges", "route_overlays", "scene_generation"],
            "total_assets": self._generation_count,
            "assets_by_type": type_counts,
        }
